name = "backend"
compatibility_date = "2023-12-01"

[vars]
JWT_SECRET="THISISOURLITTLESECRET"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYjQ4YmI5YzgtNjA4OC00YWI4LWE0YWQtNjg5OWI5NjEzNjQ3IiwidGVuYW50X2lkIjoiYTAzMDM5MDJhMzMyNzBmY2JlYjE2MDFlMzUxYzUxNmZiNTlkYWYwOTUxOGI3NzFiNTZmY2FhZjlhNGQ1MzFlNSIsImludGVybmFsX3NlY3JldCI6IjYzY2IwOTc3LTI3YWYtNDY2ZS04ZjBkLWFjMzM2NzgxOTVjNSJ9._aXCBJHyVppm7nc8eChvFb0CmsBEF2ocQT4ZpfxPh6k"

